### ISSUE TITLE
nextTimeAfter issues

### ISSUE THREAD

**Issue by NC-MXTC** [Daniel-Designs/NCTaskManager#1]
https://github.com/Daniel-Designs/NCTaskManager/blob/1b19dc066d49ebb3653ac2c72070df59c99bb958/src/main/java/mx/edu/j2se/morales/tasks/Task.java#L186-L213

What would happen if the task is non-repetitive and its time is after `current`???

**Comment by Daniel-Designs** [comment]
If it is a non-repetitive task, it goes down to the else statement (line 206), and if its "time" is after "current", it goes down to the if statement that returns the "time" (lines 207-209), and if the task is non-repetitive but "current" is after "time", it simply goes to the last return (line 212).

I donk know if that makes sense to you, if not let me know.

**Comment by NC-MXTC** [comment]
Yep, you are right! 😵‍💫
